Migrate configuration
ConductorOne/baton-jenkins pull request #13
Opened 2024-08-13 16:01 UTC by shackra

# Pull Request

To help us get this pull request reviewed and merged quickly, please be sure to include the following items:

* [ ] Tests (if applicable)
* [ ] Documentation (if applicable)
* [ ] Changelog entry
* [ ] A full explanation here in the PR description of the work done

## PR Type
What kind of change does this PR introduce?

* [ ] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] Tests
* [ ] Other

## Backward Compatibility

Is this change backward compatible with the most recently released version? Does it introduce changes which might change the user experience in any way? Does it alter the Connector in any way?

* [ ] Yes (backward compatible)
* [ ] No (breaking changes)

#### Useful links:

- [https://github.com/ConductorOne/baton-sdk/wiki/Coding-Guidelines](Baton SDK coding guidelines)
- [https://github.com/ConductorOne/baton/blob/main/CONTRIBUTING.md](New contributor guide)

## Issue Linking

## What's new?
-

2024-08-13 18:16 UTC, mgaeta commented on cmd/baton-jenkins/config.go
> +	field.FieldsRequiredTogether(username, password),
It looks like the only relationship is that `password` and `token` are mutually exclusive.

2024-08-13 18:25 UTC, mgaeta requested changes
https://www.jenkins.io/doc/book/system-administration/authenticating-scripted-clients/
I think the password and token are basically interchangeable 
```go
func WithSetBasicAuthHeader(username, password string) uhttp.RequestOption {
	return uhttp.WithHeader("Authorization", "Basic "+basicAuth(username, password))
}

func WithSetTokenAuthHeader(username, token string) uhttp.RequestOption {
	return uhttp.WithHeader("Authorization", "Basic "+basicAuth(username, token))
}
```
Also, make sure to update the help text in the README

2024-08-13 18:32 UTC, mgaeta commented on cmd/baton-jenkins/main.go
> +	if v.GetString("token") != "" {
```go
l := ctxzap.Extract(ctx)
err := field.Validate(Configuration, v)
if err != nil {
  return nil, err
}
jenkinsClient := client.NewClient().
  WithUser(v.GetString("username")).
  WithPassword(v.GetString("password")).
  WithToken(v.GetString("token"))
```

2024-08-13 22:01 UTC, shackra commented
> https://www.jenkins.io/doc/book/system-administration/authenticating-scripted-clients/ I think the password and token are basically interchangeable
> 
> ```go
> func WithSetBasicAuthHeader(username, password string) uhttp.RequestOption {
> 	return uhttp.WithHeader("Authorization", "Basic "+basicAuth(username, password))
> }
> 
> func WithSetTokenAuthHeader(username, token string) uhttp.RequestOption {
> 	return uhttp.WithHeader("Authorization", "Basic "+basicAuth(username, token))
> }
> ```
> 
> Also, make sure to update the help text in the README

the client API for Jenkins is a bit different so we cannot re-use variables to set that piece of auth information:

```go
jenkinsClient.WithUser("random-username").WithBearerToken("magic-token")

jenkinsClient.WithUser("random-username").WithPassword("secretpassword")
```

2024-08-14 16:53 UTC, mgaeta commented on cmd/baton-jenkins/config.go
> +	field.FieldsMutuallyExclusive(token, password),
I think you should also add a `FieldsAtLeastOneUsed` relationship for `token` and `password`

2024-08-14 21:20 UTC, mgaeta approved these changes

2024-08-14 21:49 UTC, shackra commented on cmd/baton-jenkins/main.go
> +	if v.GetString("token") != "" {
I mean, is that even possible without causing API errors? 😆

2024-08-14 22:36 UTC, merged